### ISSUE TITLE
DevTools failed to load source map - System error: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by shoeferlin** [JasonXian/react-chrome-extension-boilerplate#1]
Hey Jason,

Thanks for your response on Udemy. Unfortunately, I still cannot get rid of the error

`DevTools failed to load source map: Could not load content for chrome-extension://ogempahklfajmmimbhmkffiajamoamaa/contentScript.js.map: System error: net::ERR_BLOCKED_BY_CLIENT`

when using the webpack development configuration.

I cloned your boilerplate repository (https://github.com/JasonXian/react-chrome-extension-boilerplate) freshly. I am using macOS 12.4 and Chrome Version 103.0.5060.114 (Official Build) (arm64) and Node.js v16.13.1. I deactivated all other extensions (uBlock origin etc.) as they might cause this error, started Chrome in the Incognito Mode to avoid any side effects with only the unpacked boilerplate extension loaded but still the error appears in the freshly cloned boilerplate for the contentScript.js

This makes using the dev configuration of the extension boilerplate unfortunately not usable. The production configurations works like a charm but of course without helpful source map errors.

Feel free to contact me to debug together in case it is not reproducible. I tested it on another machine with Windows as OS and had the same issue.

Would highly appreciate if you can have a look on it.

Best regards,
Simon

<img width="1283" alt="Screenshot 2022-07-12 at 15 35 10" src="https://user-images.githubusercontent.com/37844541/178504271-d935445e-5bf6-48e2-aac5-985159f2063e.png">
<img width="1284" alt="Screenshot 2022-07-12 at 15 26 04" src="https://user-images.githubusercontent.com/37844541/178504288-7941b803-bf43-451f-84cc-09fb11b775a2.png">
<img width="1285" alt="Screenshot 2022-07-12 at 15 36 36" src="https://user-images.githubusercontent.com/37844541/178504216-8229cca8-c72d-49ab-bf98-d97383bd8330.png">

**Comment by JasonXian** [comment]
Hey Simon!

Thanks for reporting this issue and providing environment notes and screenshots. This made it incredibly easy to debug the issue!

I pushed a change in e7717aa that should fix the issue. The root cause is due to the Webpack [devtool](https://webpack.js.org/configuration/devtool/) configuration that was previously being used in the development setup.

Options such as `cheap-module-source-map` generate a `.js.map` file that aren't packaged properly with content scripts when injected into webpages. As a result, we get a warning that the content for the source map file can't be found. By using `inline-source-map` the original lines are maintained and the source map source is preserved in a local asset. 

Both of these options have the slowest build times, but comes with the benefit of retaining our original lines of code for easy debugging. The `eval` configurations are ideal for development builds, but can't be used in manifest version 3, as eval scripts are blocked due to security reasons.

Please let me know if this fixes the issue!

**Comment by shoeferlin** [comment]
Hey @JasonXian, 

this is amazing. Thanks for the quick fix!

Simon

**Comment by shoeferlin** [comment]
I tried different settings in that line as well but mistakenly added not only the entry points in webpacker `entry: {}` but also my internal imports which introduced another bug. Using your fix plus only using only the entry point (e.g. `contentScript.ts`) and letting webpacker resolve the dependencies (internal and external imports) made it run.
